language: node_js

sudo: required

services:
  - docker

before_install:
  - gem install bundler
  - gem install rake
  - pyenv install 2.7.8
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - docker-compose --version

script:
  - docker-compose -f ./docker-compose.yml -f ./docker-compose.test.yml build
  - docker-compose -f ./docker-compose.yml -f ./docker-compose.test.yml up -d

after_script:
  - docker-compose stop
  - docker-compose rm -f
