version: '3'

services:
  db:
    container_name: db
    image: mongo
    restart: 'always'
    ports:
      - '27017:27017'

  redis:
    container_name: redis
    image: redis
    restart: 'always'
    ports:
      - '6379:6379'
