version: '3'

services:
  server:
    container_name: server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    restart: 'always'
    volumes:
      - /app/node_modules
      - ../:/app
    links:
      - db
    env_file:
      - ../.env
    ports:
      - '4000:4000'
