version: '3'

services:
  server:
    container_name: server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: 'always'
    volumes:
      - /app/node_modules
    links:
      - db
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URI=${DATABASE_URI}
      - ISSUER=${ISSUER}
      - SUBJECT=${SUBJECT}
      - AUDIENCE=${AUDIENCE}
      - EXPIRES_IN=${EXPIRES_IN}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - '80:80'
    links:
      - db
      - server
