FROM node:8.12.0-alpine AS builder

WORKDIR /app

RUN apk add g++ make python

RUN npm install -g tsc \
  && npm install -g concurrently \
  && npm install -g typescript

COPY ./package.json ./

RUN yarn install

COPY ./ ./

EntryPoint ["yarn", "test"]